### ISSUE TITLE
Add support for macos (osx)

### ISSUE THREAD

**Issue by Ptkatz** [MichalStrehovsky/PublishAotCross#8]

**Comment by MichalStrehovsky** [comment]
I don't think this is possible. Linking .NET for macos requires providing macos frameworks. Those are only available with an xcode license. Apple doesn't really want anyone to build software for their platform without paying them first.

(PublishAotCross uses zig under the hood and as long zig doesn't support it, it's out of question for PublishAotCross https://github.com/ziglang/zig/issues/1349)

**Comment by user76-real** [comment]
https://github.com/MichalStrehovsky/PublishAotCross/issues/12
